### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by aakodadi** [tuxmaster/QtDMM#14]
Build fails on arch with the following error:

```
sources/main.cpp: In function ‘void myMessageOutput(QtMsgType, const QMessageLogContext&, const QString&)’:
sources/main.cpp:45:24: error: format not a string literal and no format arguments [-Werror=format-security]
45 |                  qFatal(QString("Fatal: %1").arg(msg).toUtf8());
cc1plus: some warnings being treated as errors
make[1]: *** [Makefile:925: ../tmp/obj/main.o] Error 1
make[1]: Leaving directory '/home/aakodadi/.local/qtdmm-qt5-git/src/qtdmm-qt5-git/src'
make: *** [Makefile:47: sub-src-make_first-ordered] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by parkerlreed** [comment]
This is with 

qt5-base 5.15.2
gcc 11.1.0-1

**Comment by tuxmaster5000** [comment]
I don't see this problem on Fedora 33 using:
gcc-10.3.1-1.fc33.x86_64
qt5-qtbase-devel-5.15.2-15.fc33.x86_64
So I can't reproduce it.

**Comment by parkerlreed** [comment]
Thanks. I'll see if I can narrow it down to GCC.

**Comment by parkerlreed** [comment]
Removed `-Wformat -Werror=format-security` from the default CFLAGS (system wide) and it works now (You have to start with clean source as they get shoved into the generate src/Makefile)

Working on gcc 11.1 removing those flags

**Comment by redPanther** [comment]
this is resolved? if so, @tuxmaster5000 can you close it?
